<a href="https://colab.research.google.com/github/darshanshenoy06/Python_analyst/blob/main/modules/Dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

In [7]:
dummy_df = pd.DataFrame({

            "Employee":["John","Mike","Sarah","Tom","Mike"],
            "Department":["IT","HR","IT","Finance","HR"],
            "Salary":[50000,60000,70000,55000,60000],
            "City":["Bangalore","Mumbai","Bangalore","Delhi","Mumbai"]

})
dummy_df.head().style.hide(axis= "index")

In [8]:
dummy_df['Department']

0         IT
1         HR
2         IT
3    Finance
4         HR
Name: Department, dtype: object

In [10]:
dummy_df

  Employee Department  Salary       City
0     John         IT   50000  Bangalore
1     Mike         HR   60000     Mumbai
2    Sarah         IT   70000  Bangalore
3      Tom    Finance   55000      Delhi
4     Mike         HR   60000     Mumbai

In [12]:
dummy_df[dummy_df['Salary']>55000].style.hide(axis='index')

In [14]:
dummy_df[(dummy_df['Department']== "HR") & (dummy_df['Salary']>= 60000)]

  Employee Department  Salary    City
1     Mike         HR   60000  Mumbai
4     Mike         HR   60000  Mumbai