<a href="https://colab.research.google.com/github/darshanshenoy06/Python_analyst/blob/main/modules/Dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
import numpy as np

In [70]:
dummy_df = pd.DataFrame({

            "Employee":["John","Mike","Sarah","Tom","Mike"],
            "Department":["IT","HR","IT","Finance","HR"],
            "Salary":[50000,60000,70000,55000,60000],
            "City":["Bangalore","Mumbai","Bangalore","Delhi","Mumbai"]

})
dummy_df.head().style.hide(axis= "index")

In [71]:
dummy_df['Department']

0         IT
1         HR
2         IT
3    Finance
4         HR
Name: Department, dtype: object

In [72]:
dummy_df

  Employee Department  Salary       City
0     John         IT   50000  Bangalore
1     Mike         HR   60000     Mumbai
2    Sarah         IT   70000  Bangalore
3      Tom    Finance   55000      Delhi
4     Mike         HR   60000     Mumbai

In [73]:
dummy_df[dummy_df['Salary']>55000].style.hide(axis='index')

In [74]:
dummy_df[(dummy_df['Department']== "HR") & (dummy_df['Salary']>= 60000)]

  Employee Department  Salary    City
1     Mike         HR   60000  Mumbai
4     Mike         HR   60000  Mumbai

In [75]:
dummy_df.sort_values("Salary",ascending=False)

  Employee Department  Salary       City
2    Sarah         IT   70000  Bangalore
4     Mike         HR   60000     Mumbai
1     Mike         HR   60000     Mumbai
3      Tom    Finance   55000      Delhi
0     John         IT   50000  Bangalore

In [76]:
missing_values = pd.DataFrame({
    "Employee":["John","Mike","Sarah","Tom"],
    "Salary":[50000,None,70000,None],
    "Department":["IT","HR","IT","Finance"]
})

In [77]:
missing_values.head()

  Employee   Salary Department
0     John  50000.0         IT
1     Mike      NaN         HR
2    Sarah  70000.0         IT
3      Tom      NaN    Finance

In [78]:
missing_values.isnull()

   Employee  Salary  Department
0     False   False       False
1     False    True       False
2     False   False       False
3     False    True       False

In [79]:
missing_values.isnull().sum()

Employee      0
Salary        2
Department    0
dtype: int64

In [80]:
missing_values['Salary'].fillna(0)

0    50000.0
1        0.0
2    70000.0
3        0.0
Name: Salary, dtype: float64

In [81]:
missing_values['Salary'].fillna(0)

0    50000.0
1        0.0
2    70000.0
3        0.0
Name: Salary, dtype: float64

In [82]:
missing_values

  Employee   Salary Department
0     John  50000.0         IT
1     Mike      NaN         HR
2    Sarah  70000.0         IT
3      Tom      NaN    Finance

In [83]:
dummy_df['Salary'] = dummy_df['Salary'].fillna(0)
dummy_df

  Employee Department  Salary       City
0     John         IT   50000  Bangalore
1     Mike         HR   60000     Mumbai
2    Sarah         IT   70000  Bangalore
3      Tom    Finance   55000      Delhi
4     Mike         HR   60000     Mumbai

Create a null Value

In [84]:
dummy_df.loc[1, 'Salary'] = None
dummy_df

  Employee Department   Salary       City
0     John         IT  50000.0  Bangalore
1     Mike         HR      NaN     Mumbai
2    Sarah         IT  70000.0  Bangalore
3      Tom    Finance  55000.0      Delhi
4     Mike         HR  60000.0     Mumbai

In [85]:
dummy_df.isnull().sum()

Employee      0
Department    0
Salary        1
City          0
dtype: int64

In [86]:
dummy_df['Salary'] = dummy_df['Salary'].fillna(0)
dummy_df

  Employee Department   Salary       City
0     John         IT  50000.0  Bangalore
1     Mike         HR      0.0     Mumbai
2    Sarah         IT  70000.0  Bangalore
3      Tom    Finance  55000.0      Delhi
4     Mike         HR  60000.0     Mumbai

In [87]:
dummy_df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [88]:
dummy_df.loc[4] = dummy_df.loc[1]
dummy_df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [89]:
dummy_df.duplicated(subset=['Department'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [90]:
test_df = pd.DataFrame({
    "Employee":["John","Mike","Sarah","Mike"],
    "Salary":[50000,60000,70000,60000]
})
test_df

  Employee  Salary
0     John   50000
1     Mike   60000
2    Sarah   70000
3     Mike   60000

In [91]:
test_df.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [92]:
test_df = test_df.dropna()
test_df

  Employee  Salary
0     John   50000
1     Mike   60000
2    Sarah   70000
3     Mike   60000

In [93]:
test_df.drop_duplicates()

  Employee  Salary
0     John   50000
1     Mike   60000
2    Sarah   70000

In [94]:
test_df.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [95]:
df_dtypes = pd.DataFrame({
    "Employee":["John","Mike"],
    "Age":[25,28],
    "Bonus":[1000.50,2000.75]
})

In [96]:
df_dtypes.dtypes

Employee     object
Age           int64
Bonus       float64
dtype: object

In [97]:
df_columns = pd.DataFrame({
    "Employee":["John","Mike","Sarah"],
    "Salary":[50000,60000,70000]
})

In [98]:
df_columns['Tax'] =  df_columns['Salary'] *(0.05)
df_columns

  Employee  Salary     Tax
0     John   50000  2500.0
1     Mike   60000  3000.0
2    Sarah   70000  3500.0

In [99]:
df_columns['Net_salary'] = df_columns['Salary'] - df_columns['Tax']
df_columns

  Employee  Salary     Tax  Net_salary
0     John   50000  2500.0     47500.0
1     Mike   60000  3000.0     57000.0
2    Sarah   70000  3500.0     66500.0

In [100]:
salary_emp_details = pd.DataFrame({
    "Employee":["John","Mike","Sarah"],
    "Salary":[50000,60000,70000]
})

In [101]:
salary_emp_details['Salary_eligiblity'] = np.where(
    salary_emp_details['Salary'] >= 60000,
    "Eligible",
    "Not Eligible"
)

In [102]:
salary_emp_details

  Employee  Salary Salary_eligiblity
0     John   50000      Not Eligible
1     Mike   60000          Eligible
2    Sarah   70000          Eligible

Output check

In [103]:
dummy_df['Department'].value_counts()

Department
IT         2
HR         2
Finance    1
Name: count, dtype: int64

Apply Concept

In [104]:
apply_df = pd.DataFrame({
    "Employee":["John","Mike","Sarah"],
    "Salary":[50000,60000,70000]
})

In [105]:
apply_df['Employee'].apply(str.upper)

0     JOHN
1     MIKE
2    SARAH
Name: Employee, dtype: object

In [106]:
def add_bonus(salary):
    return salary + 50000

In [107]:
apply_df['Salary'].apply(add_bonus)

0    100000
1    110000
2    120000
Name: Salary, dtype: int64

In [108]:
def autonomy(Salary):
  if Salary >= 60000:
    return "Senior"
  else:
    return "Junior"

In [109]:
dummy_df['Experience'] = dummy_df['Salary'].apply(autonomy)
dummy_df

  Employee Department   Salary       City Experience
0     John         IT  50000.0  Bangalore     Junior
1     Mike         HR      0.0     Mumbai     Junior
2    Sarah         IT  70000.0  Bangalore     Senior
3      Tom    Finance  55000.0      Delhi     Junior
4     Mike         HR      0.0     Mumbai     Junior

In [110]:
dummy_df['Department'].nunique()

3

In [111]:
Salary_mean = pd.DataFrame({
    "Salary" :[50000,60000,70000]
}
)

In [112]:
test_df['Salary'].describe()

count        4.000000
mean     60000.000000
std       8164.965809
min      50000.000000
25%      57500.000000
50%      60000.000000
75%      62500.000000
max      70000.000000
Name: Salary, dtype: float64

In [113]:
gb = pd.DataFrame({
    "Employee":["John","Mike","Sarah","Tom","David","Emma"],
    "Department":["IT","HR","IT","Finance","HR","IT"],
    "Gender":["M","M","F","M","M","F"],
    "Salary":[50000,60000,70000,55000,65000,80000]
})

In [114]:
gb.groupby('Department')['Salary'].sum()

Department
Finance     55000
HR         125000
IT         200000
Name: Salary, dtype: int64

In [115]:
gb.groupby("Department")["Employee"].count()

Department
Finance    1
HR         2
IT         3
Name: Employee, dtype: int64

In [116]:
gb.groupby("Department")["Salary"].agg(
    ["sum","mean","max","min","count"]
)

               sum          mean    max    min  count
Department
Finance      55000  55000.000000  55000  55000      1
HR          125000  62500.000000  65000  60000      2
IT          200000  66666.666667  80000  50000      3

In [117]:
gb.groupby(["Department","Gender"])["Salary"].mean()

Department  Gender
Finance     M         55000.0
HR          M         62500.0
IT          F         75000.0
            M         50000.0
Name: Salary, dtype: float64

In [118]:
gb.groupby(["Department","Gender"])["Salary"].mean().reset_index()

  Department Gender   Salary
0    Finance      M  55000.0
1         HR      M  62500.0
2         IT      F  75000.0
3         IT      M  50000.0

In [119]:
gb.groupby("Department").agg(
    Mean_Salary=("Salary","mean"),
    Max_Salary=("Salary","max"),
    Employee_Count=("Employee","count")
)

             Mean_Salary  Max_Salary  Employee_Count
Department
Finance     55000.000000       55000               1
HR          62500.000000       65000               2
IT          66666.666667       80000               3

In [120]:
employee_df = pd.DataFrame({
    "Employee_ID":[1,2,3,4],
    "Employee":["John","Mike","Sarah","Tom"]
})
salary_df = pd.DataFrame({
    "Employee_ID":[1,2,3],
    "Salary":[50000,60000,70000]
})

In [121]:
employee_df.merge(salary_df, on="Employee_ID")

   Employee_ID Employee  Salary
0            1     John   50000
1            2     Mike   60000
2            3    Sarah   70000

In [122]:
employee_df.merge(salary_df, on="Employee_ID", how="left")

   Employee_ID Employee   Salary
0            1     John  50000.0
1            2     Mike  60000.0
2            3    Sarah  70000.0
3            4      Tom      NaN

Direct by the the dataframe

In [123]:
gb.pivot_table(
    index="Department",
    values="Salary",
    aggfunc="mean"
)

                  Salary
Department
Finance     55000.000000
HR          62500.000000
IT          66666.666667

Direct from the pandas

In [124]:
pd.pivot_table(
    gb,
    index="Department",
    columns = "Gender",
    values="Salary",
    aggfunc="mean"
)

Gender            F        M
Department
Finance         NaN  55000.0
HR              NaN  62500.0
IT          75000.0  50000.0

Understanding difference between group by and Pivot Table

In [125]:
gb.groupby(["Department","Gender"])["Salary"].mean()

Department  Gender
Finance     M         55000.0
HR          M         62500.0
IT          F         75000.0
            M         50000.0
Name: Salary, dtype: float64

Concating Two Dataframes

In [126]:
df1 = pd.DataFrame({
    "Employee":["John","Mike"],
    "Salary":[50000,60000]
})

df2 = pd.DataFrame({
    "Employee":["Sarah","Tom"],
    "Salary":[70000,55000]
})

In [127]:
pd.concat([df1,df2],
          axis=1
          )

  Employee  Salary Employee  Salary
0     John   50000    Sarah   70000
1     Mike   60000      Tom   55000

In [131]:
gb.loc[0,'Salary'] = 75000
gb

  Employee Department Gender  Salary
0     John         IT      M   75000
1     Mike         HR      M   60000
2    Sarah         IT      F   70000
3      Tom    Finance      M   55000
4    David         HR      M   65000
5     Emma         IT      F   80000