<a href="https://colab.research.google.com/github/darshanshenoy06/Python_analyst/blob/main/modules/Dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import pandas as pd

In [66]:
dummy_df = pd.DataFrame({

            "Employee":["John","Mike","Sarah","Tom","Mike"],
            "Department":["IT","HR","IT","Finance","HR"],
            "Salary":[50000,60000,70000,55000,60000],
            "City":["Bangalore","Mumbai","Bangalore","Delhi","Mumbai"]

})
dummy_df.head().style.hide(axis= "index")

In [67]:
dummy_df['Department']

0         IT
1         HR
2         IT
3    Finance
4         HR
Name: Department, dtype: object

In [68]:
dummy_df

  Employee Department  Salary       City
0     John         IT   50000  Bangalore
1     Mike         HR   60000     Mumbai
2    Sarah         IT   70000  Bangalore
3      Tom    Finance   55000      Delhi
4     Mike         HR   60000     Mumbai

In [69]:
dummy_df[dummy_df['Salary']>55000].style.hide(axis='index')

In [70]:
dummy_df[(dummy_df['Department']== "HR") & (dummy_df['Salary']>= 60000)]

  Employee Department  Salary    City
1     Mike         HR   60000  Mumbai
4     Mike         HR   60000  Mumbai

In [71]:
dummy_df.sort_values("Salary",ascending=False)

  Employee Department  Salary       City
2    Sarah         IT   70000  Bangalore
4     Mike         HR   60000     Mumbai
1     Mike         HR   60000     Mumbai
3      Tom    Finance   55000      Delhi
0     John         IT   50000  Bangalore

In [72]:
missing_values = pd.DataFrame({
    "Employee":["John","Mike","Sarah","Tom"],
    "Salary":[50000,None,70000,None],
    "Department":["IT","HR","IT","Finance"]
})

In [73]:
missing_values.head()

  Employee   Salary Department
0     John  50000.0         IT
1     Mike      NaN         HR
2    Sarah  70000.0         IT
3      Tom      NaN    Finance

In [74]:
missing_values.isnull()

   Employee  Salary  Department
0     False   False       False
1     False    True       False
2     False   False       False
3     False    True       False

In [75]:
missing_values.isnull().sum()

Employee      0
Salary        2
Department    0
dtype: int64

In [76]:
missing_values['Salary'].fillna(0)

0    50000.0
1        0.0
2    70000.0
3        0.0
Name: Salary, dtype: float64

In [77]:
missing_values['Salary'].fillna(0)

0    50000.0
1        0.0
2    70000.0
3        0.0
Name: Salary, dtype: float64

In [78]:
missing_values

  Employee   Salary Department
0     John  50000.0         IT
1     Mike      NaN         HR
2    Sarah  70000.0         IT
3      Tom      NaN    Finance

In [80]:
dummy_df['Salary'] = dummy_df['Salary'].fillna(0)
dummy_df

  Employee Department  Salary       City
0     John         IT   50000  Bangalore
1     Mike         HR   60000     Mumbai
2    Sarah         IT   70000  Bangalore
3      Tom    Finance   55000      Delhi
4     Mike         HR   60000     Mumbai

Create a null Value

In [81]:
dummy_df.loc[1, 'Salary'] = None
dummy_df

  Employee Department   Salary       City
0     John         IT  50000.0  Bangalore
1     Mike         HR      NaN     Mumbai
2    Sarah         IT  70000.0  Bangalore
3      Tom    Finance  55000.0      Delhi
4     Mike         HR  60000.0     Mumbai

In [82]:
dummy_df.isnull().sum()

Employee      0
Department    0
Salary        1
City          0
dtype: int64

In [83]:
dummy_df['Salary'] = dummy_df['Salary'].fillna(0)
dummy_df

  Employee Department   Salary       City
0     John         IT  50000.0  Bangalore
1     Mike         HR      0.0     Mumbai
2    Sarah         IT  70000.0  Bangalore
3      Tom    Finance  55000.0      Delhi
4     Mike         HR  60000.0     Mumbai

In [84]:
dummy_df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [88]:
dummy_df.loc[4] = dummy_df.loc[1]
dummy_df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [93]:
dummy_df.duplicated(subset=['Department'])

0    False
1    False
2     True
3    False
4     True
dtype: bool